# fly.toml app configuration file generated for ref-sdk-api-test on 2025-01-31T15:33:05-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ref-sdk-test-cold-haze-1300'
primary_region = 'dfw'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
max_machines_running = 5
processes = ['app']

[[vm]]
memory = '2gb'
swap_size_mb = 512
cpu_kind = 'shared'
cpus = 2

[deploy]
release_command = 'npx prisma migrate deploy'
